-- MySQL Script generated by MySQL Workbench
-- Wed May  4 21:57:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beyourboss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beyourboss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beyourboss` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beyourboss` ;

-- -----------------------------------------------------
-- Table `beyourboss`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beyourboss`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(8) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `district` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `id_user` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_endereco` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beyourboss`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_credentials` TEXT NOT NULL,
  `id_address` INT NOT NULL,
  `biography` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_address_user`
    FOREIGN KEY (`id_address`)
    REFERENCES `beyourboss`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beyourboss`.`service_solicitation`
-- -----------------------------------------------------
CREATE TABLE `service_solicitation` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`id_usuario` INT(10) NOT NULL,
	`id_categoria` INT(10) NOT NULL,
	`titulo` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`descricao` TEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`nivel_prioridade` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`valor` FLOAT NOT NULL DEFAULT '0',
	`status` ENUM('ATIVO','ENCERRADO','CANCELADO') NOT NULL DEFAULT 'ATIVO' COLLATE 'utf8mb4_0900_ai_ci',
	`date_ad` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `FK_service_solicitation_user` (`id_usuario`) USING BTREE,
	INDEX `fk_service_solicitation_categoria` (`id_categoria`) USING BTREE,
	CONSTRAINT `fk_service_solicitation_categoria` FOREIGN KEY (`id_categoria`) REFERENCES `beyourboss`.`categoria` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK_service_solicitation_user` FOREIGN KEY (`id_usuario`) REFERENCES `beyourboss`.`user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=198
;



-- -----------------------------------------------------
-- Table `beyourboss`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`budget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_service_solicitation` INT NOT NULL,
  `id_user` INT NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT '0',
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `status` ENUM('PENDENTE', 'APROVADO', 'RECUSADO') NOT NULL DEFAULT 'PENDENTE',
  PRIMARY KEY (`id`),
  INDEX `fk_solicitation_service_budget` (`id_service_solicitation` ASC) VISIBLE,
  INDEX `fk_user_budget_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_solicitation_service_budget`
    FOREIGN KEY (`id_service_solicitation`)
    REFERENCES `beyourboss`.`service_solicitation` (`id`),
  CONSTRAINT `fk_user_budget`
    FOREIGN KEY (`id_user`)
    REFERENCES `beyourboss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beyourboss`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_contato` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_contact`
    FOREIGN KEY (`id_user`)
    REFERENCES `beyourboss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beyourboss`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beyourboss`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_service_solicitation` INT NOT NULL,
  `id_contractor` INT NOT NULL,
  `id_prestador` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `amount` FLOAT NOT NULL DEFAULT '0',
  `status` ENUM('EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'EM ANDAMENTO',
  `observation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_solicitation_services` USING BTREE (`id_service_solicitation`) VISIBLE,
  INDEX `FK_services_user` (`id_contractor` ASC) VISIBLE,
  INDEX `FK_services_user_2` (`id_prestador` ASC) VISIBLE,
  CONSTRAINT `fk_service_solicitation_services`
    FOREIGN KEY (`id_service_solicitation`)
    REFERENCES `beyourboss`.`service_solicitation` (`id`),
  CONSTRAINT `FK_services_user`
    FOREIGN KEY (`id_contractor`)
    REFERENCES `beyourboss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_services_user_2`
    FOREIGN KEY (`id_prestador`)
    REFERENCES `beyourboss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
