# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .
    container_name: app-beyourboss
    networks:
      - my-network-beyourboss
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: db-beyourboss
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --innodb-use-native-aio=0
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - /mysql_data_beyourboss:/var/lib/mysql

    restart: always
    ports:
      - 3306:3306
    networks:
      - my-network-beyourboss
    environment:
      - MYSQL_DATABASE=beyourboss_bd
      - MYSQL_ROOT_PASSWORD=rootadmin
      - MYSQL_USER=admin

  adminer:
    image: adminer
    container_name: adminer-beyourboss
    networks:
      - my-network-beyourboss
    restart: always
    ports:
      - 8081:8080
volumes:
  mysql_data_beyourboss:
    external: true
networks:
  my-network-beyourboss:
    driver: bridge
